{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:ultrajson_project:ultrajson:*:*:*:*:*:python:*:*"
        ],
        "fix_commit": "https://github.com/ultrajson/ultrajson/commit/67ec07183342589d602e0fcf7bb1ff3e19272687",
        "version_end_excluding": {
            "ultrajson_project:ultrajson": "5.4.0"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "C",
    "licences": {
        "database": "",
        "affected_repository": "Other"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2022-31116"
        ],
        "CWE": [
            "CWE-670"
        ]
    }
}