{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:yetiforce:yetiforce_customer_relationship_management:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/yetiforcecompany/yetiforcecrm/commit/6b5967198e43b6fbb3b2715b49c6cd5b12ce08c3",
        "version_end_excluding": {
            "yetiforce:yetiforce_customer_relationship_management": "unknown"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PHP",
    "licences": {
        "database": "",
        "affected_repository": "Other"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2021-4121"
        ],
        "CWE": [
            "CWE-79"
        ]
    }
}