{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:redhat:ansible_automation_platform_early_access:2.0:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/ansible/ansible/commit/fe28767970c8ec62aabe493c46b53a5de1e5fac0",
        "version_end_excluding": {
            "redhat:ansible_automation_platform_early_access": "unknown"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "GNU General Public License v3.0"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2021-3620"
        ],
        "CWE": [
            "CWE-209"
        ]
    }
}