{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:jupyter:jupyter_server:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/jupyter-server/jupyter_server/commit/a5683aca0b0e412672ac6218d09f74d44ca0de5a",
        "version_end_excluding": {
            "jupyter:jupyter_server": "1.15.4"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "BSD 3-Clause \"New\" or \"Revised\" License"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2022-24757"
        ],
        "CWE": [
            "CWE-532"
        ]
    }
}