{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:vonautomatisch:django_grappelli:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/sehmaschine/django-grappelli/commit/4ca94bcda0fa2720594506853d85e00c8212968f",
        "version_end_excluding": {
            "vonautomatisch:django_grappelli": "2.15.2"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "Other"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2021-46898"
        ],
        "CWE": []
    }
}