{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:ipython:ipython:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/ipython/ipython/commit/46a51ed69cdf41b4333943d9ceeb945c4ede5668",
        "version_end_excluding": {
            "ipython:ipython": "unknown"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "BSD 3-Clause \"New\" or \"Revised\" License"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2022-21699"
        ],
        "CWE": [
            "CWE-250",
            "CWE-279"
        ]
    }
}