{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/python/cpython/commit/4eaf4891c12589e3c7bdad5f5b076e4c8392dd06",
        "version_end_excluding": {
            "python:python": "3.8.20"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "Other"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2024-6232"
        ],
        "CWE": [
            "CWE-1333"
        ]
    }
}