{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:zope:zope:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/zopefoundation/Zope/commit/26a55dbc301db417f47cafda6fe0f983b5690088",
        "version_end_excluding": {
            "zope:zope": "4.8.10"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "Other"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2023-42458"
        ],
        "CWE": [
            "CWE-80",
            "CWE-79"
        ]
    }
}