{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:jupyter:jupyter_server_proxy:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/jupyterhub/jupyter-server-proxy/commit/fd31930bacd12188c448c886e0783529436b99eb",
        "version_end_excluding": {
            "jupyter:jupyter_server_proxy": "3.2.1"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "BSD 3-Clause \"New\" or \"Revised\" License"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2022-21697"
        ],
        "CWE": [
            "CWE-918"
        ]
    }
}