{
    "original_source": {
        "database(url)": "https://github.com/secureIT-project/CVEfixes",
        "software_system(CPE)": [
            "cpe:2.3:a:openapi-python-client_project:openapi-python-client:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/triaxtec/openapi-python-client/commit/3e7dfae5d0b3685abf1ede1bc6c086a116ac4746",
        "version_end_excluding": {
            "openapi-python-client_project:openapi-python-client": "0.5.3"
        },
        "path": {
            "file_path": "tests/test_templates/conftest.py"
        }
    },
    "programming_language": "python",
    "licences": {
        "database": "MIT",
        "affected_repository": "MIT License"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2020-15141"
        ],
        "CWE": [
            "CWE-22"
        ]
    }
}