{
    "original_source": {
        "database(url)": "https://github.com/secureIT-project/CVEfixes",
        "software_system(CPE)": [
            "cpe:2.3:a:matrix:synapse:*:*:*:*:*:*:*:*",
            "cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/matrix-org/synapse/commit/30fba6210834a4ecd91badf0c8f3eb278b72e746",
        "version_end_excluding": {
            "matrix:synapse": "1.25.0",
            "fedoraproject:fedora": "unknown"
        },
        "path": {
            "file_path": "synapse/app/generic_worker.py"
        }
    },
    "programming_language": "python",
    "licences": {
        "database": "MIT",
        "affected_repository": "Apache License 2.0"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2021-21273"
        ],
        "CWE": [
            "CWE-601"
        ]
    }
}